CREATE TYPE alignment_choice AS ENUM (
    'Lawful-Good',
    'Neutral-Good',
    'Chaotic-Good',
    'Lawful-Neutral',
    'Neutral',
    'Chaotic-Neutral',
    'Lawful-Evil',
    'Neutral-Evil',
    'Chaotic-Evil'
);

CREATE TABLE IF NOT EXISTS character_info (
id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
player_id INTEGER 
    REFERENCES diary_users(id) ON DELETE CASCADE NOT NULL,
date_created TIMESTAMPTZ DEFAULT now() NOT NULL,
character_name TEXT NOT NULL, 
race  TEXT NOT NULL, /* ENUM for update*/
background TEXT NOT NULL, 
alignment alignment_choice NOT NULL DEFAULT 'Neutral',
personality_traits TEXT NOT NULL,
ideals TEXT NOT NULL,
bonds TEXT NOT NULL,
flaws TEXT NOT NULL
);