CREATE TYPE item_types AS ENUM (
    'Armor',
    'Ammo',
    'Potions',
    'Rings',
    'Rods',
    'Scrolls',
    'Staves',
    'Wands',
    'Wonderous Items',
    'Miscellaneous'
);


CREATE TABLE IF NOT EXISTS item_details(
id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
item_name TEXT NOT NULL,
catagory item_types DEFAULT 'Miscellaneous' NOT NULL,
item_disccription TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS item_inventory (
id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
item_id INTEGER
    REFERENCES item_details(id) ON DELETE CASCADE NOT NULL,
character_id INTEGER
    REFERENCES character_sheet(id) ON DELETE CASCADE NOT NULL
);