CREATE TABLE IF NOT EXISTS feature_trait_details( 
id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
feature_trait_name TEXT NOT NULL, 
feature_trait_discription TEXT NOT NULL
/*effects... this one is going to be hard but is seem like something neet to work on in post grade*/
);

CREATE TABLE IF NOT EXISTS features_and_traits(
id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
feature_trait_id INTEGER
    REFERENCES feature_trait_details(id) ON DELETE CASCADE NOT NULL,
character_id INTEGER
    REFERENCES character_sheet(id) ON DELETE CASCADE NOT NULL
);