/*                                List of relations
 Schema |             Name             |   Type   | Owner |    Size    | Description
--------+------------------------------+----------+-------+------------+-------------
 public | character_info               | table    | Green | 8192 bytes |[]
 public | character_info_id_seq        | sequence | Green | 8192 bytes |[]
 public | character_sheet              | table    | Green | 8192 bytes |[]
 public | character_sheet_id_seq       | sequence | Green | 8192 bytes |[]
 public | class_details                | table    | Green | 8192 bytes |[]
 public | class_details_id_seq         | sequence | Green | 8192 bytes |[]
 public | classes_and_levels           | table    | Green | 0 bytes    |[]
 public | classes_and_levels_id_seq    | sequence | Green | 8192 bytes |[]
 public | diary_users                  | table    | Green | 8192 bytes |[W]<=
 public | diary_users_id_seq           | sequence | Green | 8192 bytes |[]
 public | feature_trait_details        | table    | Green | 8192 bytes |[]
 public | feature_trait_details_id_seq | sequence | Green | 8192 bytes |[]
 public | features_and_traits          | table    | Green | 0 bytes    |[]
 public | features_and_traits_id_seq   | sequence | Green | 8192 bytes |[]
 public | item_details                 | table    | Green | 8192 bytes |[]
 public | item_details_id_seq          | sequence | Green | 8192 bytes |[]
 public | item_inventory               | table    | Green | 0 bytes    |[]
 public | item_inventory_id_seq        | sequence | Green | 8192 bytes |[]
 public | schemaversion                | table    | Green | 16 kB      |
 public | weapon_details               | table    | Green | 8192 bytes |[]
 public | weapon_details_id_seq        | sequence | Green | 8192 bytes |[]
 public | weapon_inventory             | table    | Green | 0 bytes    |[]
 public | weapon_inventory_id_seq      | sequence | Green | 8192 bytes |[]
(23 rows)*/


BEGIN;

TRUNCATE
    features_and_traits,
    feature_trait_details,
    item_inventory,
    item_details,
    weapon_inventory,
    weapon_details,
    character_sheet,
    classes_and_levels,
    class_details,
    character_info,
    diary_users
    RESTART IDENTITY CASCADE;
 /*                                                          Table "public.diary_users"
    Column     |           Type           | Collation | Nullable |             Default              | Storage  | Stats target | Description
---------------+--------------------------+-----------+----------+----------------------------------+----------+--------------+-------------
 id            | integer                  |           | not null | generated by default as identity | plain    |              |
 irl_name      | text                     |           | not null |                                  | extended |              |
 user_name     | text                     |           | not null |                                  | extended |              |
 user_password | text                     |           | not null |                                  | extended |              |
 date_created  | timestamp with time zone |           | not null | now()                            | plain    |              |
*/

INSERT INTO IF EXISTS diary_users(irl_name,user_name,user_password)
VALUES
    ('gage','nomad','ligma'),
    ('ty','sat','sat-password'),
    ('dave','worm','worm-password'),
    ('holly','cast','cast-password');

/*                                                        Table "public.character_info"
       Column       |           Type           | Collation | Nullable |             Default              | Storage  | Stats target | Description
--------------------+--------------------------+-----------+----------+----------------------------------+----------+--------------+-------------
 id                 | integer                  |           | not null | generated by default as identity | plain    |              |
 player_id          | integer                  |           | not null |                                  | plain    |              |
 date_created       | timestamp with time zone |           | not null | now()                            | plain    |              |
 character_name     | text                     |           | not null |                                  | extended |              |
 race               | text                     |           | not null |                                  | extended |              |
 background         | text                     |           | not null |                                  | extended |              |
 alignment          | alignment_choice         |           | not null | 'Neutral'::alignment_choice      | plain    |              |
 personality_traits | text                     |           | not null |                                  | extended |              |
 ideals             | text                     |           | not null |                                  | extended |              |
 bonds              | text                     |           | not null |                                  | extended |              |
 flaws              | text                     |           | not null |                                  | extended |              |
        alignment_choice
        |Lawful-Good    +|
        |Neutral-Good   +|
        |Chaotic-Good   +|
        |Lawful-Neutral +|
        |Neutral        +|
        |Chaotic-Neutral+|
        |Lawful-Evil    +|
        |Neutral-Evil   +|
        |Chaotic-Evil    |

*/

INSERT INTO IF EXISTS character_info (player_id,character_name,race,background,alignment,personality_traits,ideals,bonds,flaws)
VALUES
    (1,
    'Little Light',
    'Tiefling',
    'Smuggler',
    'Chaotic-Good',
    "life is to short so squander away coins, and jems. the only thing that's worth anything, is a smile",
    "stealing is for fools that can't enjoy life as it is.",
    "someone that i was look after died in my care, i will never let that happen again",
    "I let my emotions get the best of me"
    ),
    (3,
    'Bright Phelaia',
    'Tiefling',
    'Criminal',
    'Chaotic-Neutral',
    "there is nothing better then haveing good friends, regardles of who they are",
    "I want nothing more then to live my life how i see fit (freedom)",
    "I hate what I've done, and I want to atton for my sins",
    "I'm not good under preshor, I will run if things start to look bad"
    ),
    (4,
    'Estel Ullulmem',
    'High Elf',
    'Soldier(officer)',
    'Chaotic-Good',
    "Not when shy when it comes to getting into fights, it's all in good fun I say",
    "Fight smart! & with care for those around me.",
    "I fight for those who can't do so for them selfs (for greater good)",
    "If it can help, I will take it"
    ),
    /**/
    (2,
    'Durlok BrightHammer',
    'Hill Dwarf',
    'Guild Artisan',
    'Chaotic-Good',
    "I like to talk about my profession... At Length",
    "Explore as much of the world as passible and expirience the variety of architecture and Stone Structors",
    "I will one dat return to my Guild And share my Knowledge",
    "I'm quick to assume that peopel are trying to cheat me, especially humans"
    ),
    (2,
    'Lift With Ease (E''s'')',
    'Tabaxi',
    'Sailor',
    'Chaotic-Good',
    "Work Hard/ Party Hard! Spends Gold on partys/gifts/ [curiosity] = elastic hair ties",
    "what the point of like if it's by someone elses rules(freedom)",
    "Cheated out of a Fair share, Waiting to get Due",
    "Hubris"
    );

/*                                                class_details
 id          | integer |           | not null | generated by default as identity | plain    |              |
 class_name  | text    |           | not null |                                  | extended |              |
 subclass    | text    |           |          |                                  | extended |              |
 class_level | integer |           | not null |                                  | plain    |              |
 */
INSERT INTO IF EXISTS class_details (class_name,subclass,class_level)
VALUES
    /*1*/('Druid','Circle of Land (Under Dark)',11),
    /*1*/('Rouge','',1),
    /*2*/('Wizard','Evocation',4),
    /*3*/('Fighter','Battle Master',3),
    /*3*/('Sorcerer','Divine',9),
    /*4*/('Cleric','War',4);
    /*5*/('Rougee','Swashbuckler',4),
/*
        id           | integer |           | not null | generated by default as identity 
        character_id | integer |           | not null |                                  
        class_id     | integer |           | not null |                                  
*/ 

INSERT INTO IF EXISTS classes_and_levels (character_id,class_id) 
VALUES 
    (1,1),
    (1,2),
    (2,3),
    (3,4),
    (3,5),
    (4,6),
    (5,7);

/*                                                        Table "public.character_sheet"
                Column                 |  Type   | Collation | Nullable |             Default              | Storage  | Stats target | Description
---------------------------------------+---------+-----------+----------+----------------------------------+----------+--------------+-------------
 id                                    | integer |           | not null | generated by default as identity | plain    |              |
 character_id                          | integer |           | not null |                                  | plain    |              |
 experience_points                     | integer |           | not null |                                  | plain    |              |
 proficency                            | integer |           | not null |                                  | plain    |              |
 strength                              | integer |           | not null | 10                               | plain    |              |
 strength_saving_throws_proficency     | boolean |           | not null | false                            | plain    |              |
 dexterity                             | integer |           | not null | 10                               | plain    |              |
 decterity_saving_throws_proficency    | boolean |           | not null | false                            | plain    |              |
 constitution                          | integer |           | not null | 10                               | plain    |              |
 constitution_saving_throws_proficency | boolean |           | not null | false                            | plain    |              |
 intelligence                          | integer |           | not null | 10                               | plain    |              |
 intelligence_saving_throws_proficency | boolean |           | not null | false                            | plain    |              |
 wisdom                                | integer |           | not null | 10                               | plain    |              |
 wisdom_saving_throws_proficency       | boolean |           | not null | false                            | plain    |              |
 charisma                              | integer |           | not null | 10                               | plain    |              |
 charisma_saving_throws_proficency     | boolean |           | not null | false                            | plain    |              |
 acrobatics_proficency                 | boolean |           | not null | false                            | plain    |              |
 animal_handling_proficency            | boolean |           | not null | false                            | plain    |              |
 arcana_proficency                     | boolean |           | not null | false                            | plain    |              |
 athletics_proficency                  | boolean |           | not null | false                            | plain    |              |
 deception_proficency                  | boolean |           | not null | false                            | plain    |              |
 history_proficency                    | boolean |           | not null | false                            | plain    |              |
 insight_proficency                    | boolean |           | not null | false                            | plain    |              |
 intimidation_proficency               | boolean |           | not null | false                            | plain    |              |
 investigation_proficency              | boolean |           | not null | false                            | plain    |              |
 medicine_proficency                   | boolean |           | not null | false                            | plain    |              |
 nature_proficency                     | boolean |           | not null | false                            | plain    |              |
 perception_proficency                 | boolean |           | not null | false                            | plain    |              |
 performance_proficency                | boolean |           | not null | false                            | plain    |              |
 persuasion_proficency                 | boolean |           | not null | false                            | plain    |              |
 religon_proficency                    | boolean |           | not null | false                            | plain    |              |
 sleight_of_hand_proficency            | boolean |           | not null | false                            | plain    |              |
 stealth_proficency                    | boolean |           | not null | false                            | plain    |              |
 survival_proficency                   | boolean |           | not null | false                            | plain    |              |
 other_proficiencies_and_languages     | text    |           |          |                                  | extended |              |
 armor_class                           | integer |           | not null |                                  | plain    |              |
 speed                                 | integer |           | not null |                                  | plain    |              |
 max_hit_points                        | integer |           | not null |                                  | plain    |              |
 temporary_hit_points                  | integer |           | not null | 0                                | plain    |              |
 current_hit_points                    | integer |           | not null |                                  | plain    |              |
 hit_dice                              | text    |           | not null |                                  | extended |              |
 death_saves_successe                  | integer |           | not null | 0                                | plain    |              |
 death_saves_failures                  | integer |           | not null | 0                                | plain    |              |
 attack_and_spellcasting_info          | text    |           | not null |                                  | extended |              |
 copper_prices                         | integer |           | not null | 0                                | plain    |              |
 silver_prices                         | integer |           | not null | 0                                | plain    |              |
 electrum_prices                       | integer |           | not null | 0                                | plain    |              |
 gold_prices                           | integer |           | not null | 0                                | plain    |              |
 platinum_prices                       | integer |           | not null | 0                                | plain    |              |
*/
/*god.... why did i do this to myself*/
INSERT INTO IF EXISTS character_sheet (
    character_id,
    experience_points,
    proficency,
    strength,
    strength_saving_throws_proficency,
    dexterity,
    decterity_saving_throws_proficency,
    constitution,
    constitution_saving_throws_proficency,
    intelligence,
    intelligence_saving_throws_proficency,
    wisdom,
    wisdom_saving_throws_proficency,
    charisma,
    charisma_saving_throws_proficency,
    acrobatics_proficency,
    animal_handling_proficency,
    arcana_proficency,
    athletics_proficency,
    deception_proficency,
    history_proficency,
    insight_proficency,
    intimidation_proficency,
    investigation_proficency,
    medicine_proficency,
    nature_proficency,
    perception_proficency,
    performance_proficency,
    persuasion_proficency,
    religon_proficency,
    sleight_of_hand_proficency,
    stealth_proficency,
    survival_proficency,
    other_proficiencies_and_languages,
    armor_class,
    speed,
    max_hit_points,
    temporary_hit_points,
    current_hit_points,
    hit_dice,
    death_saves_successe,
    death_saves_failures,
    attack_and_spellcasting_info,
    copper_prices,
    silver_prices,
    electrum_prices,
    gold_prices,
    platinum_prices,
)
VALUES
    (
    1,
    115150,
    4,
    11,
    false,
    16,
    false,
    14,
    false,
    14,
    true,
    16,
    true,
    14,
    false,
    true,
    false,
    true,
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    true,
    true,
    false,
    "[lang] Common, Under common, Infernal, Druidic. [other pros] Light/Mid Armor & Shields(non-metal) Club, dagger, dart, javelins, mace, quurter staff, Scimitars, sickles, slings, spears [Tools] Cheese , Theif Tools ",
    15,
    40,
    78,
    0,
    0,
    "12-d8",
    1,
    3,
    "THIS SHOULD BE ABLE TO BE NULL.....OPPSE",
    100,
    191,
    0,
    185,
    3,
    ),
    (
    2,
    3400,
    2,
    9,
    false,
    10,
    false,
    14,
    false,
    18,
    true,
    16,
    true,
    8,
    false,
    false,
    false,
    true,
    false,
    true,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    "blaob of text",
    10,
    30,
    25,
    0,
    25,
    "46d",
    0,
    0,
    "fix to be null",
    10,
    10,
    0,
    1,
    0,
    ),
    (
    3,
    100000,
    4,
    14,
    true,
    18,
    false,
    19,
    true,
    18,
    false,
    13,
    false,
    18,
    false,
    true,
    false,
    false,
    true,
    false,
    true,
    false,
    true,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    "[lang] com, Elvish, Draconic,[tools] cards, vehieles, cartographer, [armor] all [wep] all",
    17,
    30,
    106,
    0,
    106,
    "3d10 , 9d6",
    0,
    0,
    "things",
    0,
    28,
    0,
    687,
    0,
    ),
    (
    4,
    3000,
    2,
    17,
    false,
    17,
    true,
    16,
    false,
    9,
    true,
    15,
    false,
    15,
    false,
    true,
    false,
    false,
    true,
    false,
    false,
    false,
    true,
    false,
    false,
    false,
    true,
    true,
    false,
    false,
    true,
    true,
    false,
    "Navigator's tools, Vehicles(water)",
    14,
    30,
    31,
    0,
    31,
    "4d8",
    0,
    0,
    "none",
    0,
    0,
    0,
    38,
    0,
    ),
    (
    5,
    3200,
    2,
    20,
    false,
    9,
    false,
    15,
    false,
    8,
    false,
    18,
    true,
    14,
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    true,
    false,
    false,
    true,
    false,
    false,
    false,
    true,
    true,
    false,
    false,
    false,
    "[lng] common, dwarvin, elven",
    18,
    25,
    26,
    0,
    36,
    "4d8",
    0,
    0,
    "20 Bolts",
    0,
    0,
    0,
    135,
    0,
    );


/*                                                 Table "public.weapon_details"
       Column       |  Type   | Collation | Nullable |             Default              | Storage  | Stats target | Description
--------------------+---------+-----------+----------+----------------------------------+----------+--------------+-------------
 id                 | integer |           | not null | generated by default as identity | plain    |              |
 weapon_name        | text    |           | not null |                                  | extended |              |
 attack_bonus       | integer |           | not null |                                  | plain    |              |
 damage_type        | text    |           | not null | '1D4'::text                      | extended |              |
 weapon_description | text    |           |          |                                  | extended |              |
*/

INSERT INTO IF EXISTS weapon_details (weapon_name,attack_bonus,damage_type,weapon_description)
VALUES
    /*5*/('warhammer',7,'d8/blunt',"it's a large hammer that's good for denging in hevily armored things "),
    /*5*/('crowsbow',1,'d6/percing [range]100/400 two-hanged','any one can use it, even a child. if that child has the strangth to pull the string'),
    /*4, 3*/('Rapier',5,'1d6 per, finese',"A light and skinny sword made of steel, it best in the hand of someone that's quick"),
    /*4*/('shortbow',5,'1d6 [range] 80/320',' a small bow that can lonch arrows afar'),
    /*3*/('LongBow',1,'1d6[range] 150/600','a large bow with a high pull waite'),
    /*1*/('Deep Crystal Scimitar',7,'1d6 slashing magic','[slots 5/5][1d6 fire] by casting spells into the sword using an action, you may fill up one slot of the sword with respected element of the spell casted'),
    /*1*/('Scimitar',7,'1d6, finese','a curved sword, with a quick flick of the wrist this sword can leave a deep cut'),
    /*2*/('dagger',5,'1d4 [thrown]20/60 ',"a small blade thats easy to use and easier to conceal"),
    /*2*/('quarterstaff',2,'1d6 one-hand,1d8 two-handed',"it might just look like a fancy stick.... till you get hit with it"),

/*                                               Table "public.weapon_inventory"
    Column    |  Type   | Collation | Nullable |             Default              | Storage | Stats target | Description
--------------+---------+-----------+----------+----------------------------------+---------+--------------+-------------
 id           | integer |           | not null | generated by default as identity | plain   |              |
 weapon_id    | integer |           | not null |                                  | plain   |              |
 character_id | integer |           | not null |                                  | plain   |              |
*/

INSERT INTO IF EXISTS weapon_inventory (weapon_id,character_id)
VALUES
    (1,5),
    (2,5),
    (3,4),
    (3,3),
    (4,4),
    (5,3),
    (5,1),
    (7,1),
    (8,2),
    (9,2); 

/*                                                   Table "public.item_details"
      Column       |    Type    | Collation | Nullable |             Default              | Storage  | Stats target | Description
-------------------+------------+-----------+----------+----------------------------------+----------+--------------+-------------
 id                | integer    |           | not null | generated by default as identity | plain    |              |
 item_name         | text       |           | not null |                                  | extended |              |
 catagory          | item_types |           | not null | 'Miscellaneous'::item_types      | plain    |              |
 item_disccription | text       |           | not null |                                  | extended |              |

                                            List of item_types
                                            |    Elements     |
                                            +-----------------+
                                            | Armor          +|
                                            | Ammo           +|
                                            | Potions        +|
                                            | Rings          +|
                                            | Rods           +|
                                            | Scrolls        +|
                                            | Staves         +|
                                            | Wands          +|
                                            | Wonderous Items+|
                                            | Miscellaneous   |
*/    

INSERT INTO IF EXISTS item_details (item_name, catagory, item_details)
VALUES
    /*2.4.5*/('potion of healing','Potions','small potion that cure minor wonds 2d4 + 2'),
    /*1.3*/('potion of greater healing','Potions','medium sized vile of red liquid heals 4d4 + 4'),
    /*1*/('Chess Set','Miscellaneous','Chess is a board game for two players. It is played in a square board, made of 64 smaller squares, and 32 play peaces'),
    /*1.2.4*/('Theif tools','Miscellaneous',"a lock pick set with trap disarming tools, don't let the guards know you have this... they might think your put to not good" ),
    /*1.4*/('Hide Armor','Armor','AC12 + dex mod (max of 2)'),
    /*5.3*/('Full Plate Armor','Armor','18 [Disadvantage on stelth]'),
    /*1*/('Dark clothes','Miscellaneous','clothes dark in color are greate for blending into crowds of huging allys at night'),
    /*all*/('Rope [hemp]','Miscellaneous','comes in 50ft bundles, ever adventure should have it '),
    /*3.5*/('Shield','Armor',' held on one hand, can block incoming attacks [+2 to AC, when held]');


/*
                                              Table "public.item_inventory"
    Column    |  Type   | Collation | Nullable |             Default              | Storage | Stats target | Description
--------------+---------+-----------+----------+----------------------------------+---------+--------------+-------------
 id           | integer |           | not null | generated by default as identity | plain   |              |
 item_id      | integer |           | not null |                                  | plain   |              |
 character_id | integer |           | not null |                                  | plain   |              |
 crap... i forgot 'quantity....' 
*/

INSERT INTO IF EXISTS item_inventory (item_id,character_id)
VALUES
    (1,2),
    (1,4),
    (1,5),
    (2,1),
    (2,3),
    (3,1),
    (4,1),
    (4,2),
    (4,4),
    (5,5),
    (5,3),
    (6,1),
    (7,1),
    (7,2),
    (7,3),
    (7,4),
    (7,5),
    (8,3),
    (8,5);

    
/*          Column           |  Type   | Collation | Nullable |             Default              | Storage  | Stats target | Description
---------------------------+---------+-----------+----------+----------------------------------+----------+--------------+-------------
 id                        | integer |           | not null | generated by default as identity | plain    |              |
 feature_trait_name        | text    |           | not null |                                  | extended |              |
 feature_trait_discription | text    |           | not null |                                  | extended |              |
*/
INSERT INTO IF EXISTS feature_trait_details (feature_trait_name, feature_trait_discription)
VALUES
    ('',''), 

INSERT INTO IF EXISTS features_and_traits ()
VALUES
    (), 


COMMIT;